In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.drop(['Cabin','PassengerId'],axis=1, inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 69.7+ KB

In [8]:
df['Age'].fillna(df["Age"].mean(),inplace=True)

In [9]:
df.dropna(subset=['Embarked'],inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Name      889 non-null    object
 3   Sex       889 non-null    object
 4   Age       889 non-null    float64
 5   SibSp     889 non-null    int64
 6   Parch     889 non-null    int64
 7   Ticket    889 non-null    object
 8   Fare      889 non-null    float64
 9   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 76.4+ KB

# Label Encoding

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [13]:
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

In [14]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,0
2,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,2
4,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,2

In [15]:
df.drop(['Name','Ticket'],axis=1, inplace=True)

In [16]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [17]:
X = df.drop('Survived', axis=1)
y = df['Survived']

# Logistic regression

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [22]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: Survived, Length: 178, dtype: int64

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [24]:
accuracy_score(y_test,y_pred)

0.7808988764044944

In [25]:
confusion_matrix(y_test,y_pred)

array([[85, 24],
       [15, 54]], dtype=int64)

In [26]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.78      0.81       109
           1       0.69      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.79      0.78      0.78       178

# Feature Scaling for KNN

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [28]:
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[-1.58410418, -1.40530972, -0.59963554, ..., -0.4756437 ,
         2.43059683,  0.58770431],
       [ 0.8122747 , -1.40530972, -0.01249955, ..., -0.4756437 ,
        -0.35813533, -1.95246446],
       [ 0.8122747 ,  0.71158691,  0.16296612, ..., -0.4756437 ,
        -0.49094895,  0.58770431],
       ...,
       [-1.58410418, -1.40530972,  1.38312878, ..., -0.4756437 ,
        -0.12471679,  0.58770431],
       [ 0.8122747 , -1.40530972, -0.67589571, ...,  2.01099358,
         0.04708333,  0.58770431],
       [ 0.8122747 ,  0.71158691,  0.23922629, ..., -0.4756437 ,
        -0.47611594,  0.58770431]])

In [29]:
X_test_scaled = scaler.fit_transform(X_test)
X_test_scaled

array([[ 0.87837838,  0.83380939, -0.06636703, ..., -0.46915523,
        -0.47215047,  0.5836712 ],
       [-1.52702703, -1.19931487, -1.20458188, ...,  1.98701037,
         1.69902381,  0.5836712 ],
       [ 0.87837838, -1.19931487, -1.20458188, ..., -0.46915523,
        -0.40656752, -1.88998295],
       ...,
       [ 0.87837838, -1.19931487,  0.74664358, ...,  5.67125876,
        -0.01653915,  0.5836712 ],
       [ 0.87837838, -1.19931487,  0.34013828, ..., -0.46915523,
        -0.31734953,  0.5836712 ],
       [ 0.87837838, -1.19931487, -2.01759249, ...,  0.75892757,
        -0.30089329,  0.5836712 ]])

# KNN

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [31]:
knn_model = KNeighborsClassifier(n_neighbors= 5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [32]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [33]:
accuracy_score(y_test,y_pred_knn)

0.7921348314606742

In [34]:
confusion_matrix(y_test,y_pred_knn)

array([[90, 19],
       [18, 51]], dtype=int64)

In [35]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83       109
           1       0.73      0.74      0.73        69

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178

In [36]:
X_train

     Pclass  Sex        Age  SibSp  Parch      Fare  Embarked
708       1    0  22.000000      0      0  151.5500         2
240       3    0  29.699118      1      0   14.4542         0
382       3    1  32.000000      0      0    7.9250         2
792       3    0  29.699118      8      2   69.5500         2
683       3    1  14.000000      5      2   46.9000         2
..      ...  ...        ...    ...    ...       ...       ...
107       3    1  29.699118      0      0    7.7750         2
271       3    1  25.000000      0      0    0.0000         2
862       1    0  48.000000      0      0   25.9292         2
436       3    0  21.000000      2      2   34.3750         2
103       3    1  33.000000      0      0    8.6542         2

[711 rows x 7 columns]

# Naive Bayes

In [37]:
from sklearn.naive_bayes import GaussianNB

In [38]:
model_NB = GaussianNB()

In [39]:
model_NB.fit(X_train,y_train)

GaussianNB()

In [40]:
y_pred_NB = model_NB.predict(X_test)

In [41]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1], dtype=int64)

In [42]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: Survived, Length: 178, dtype: int64

In [43]:
accuracy_score(y_test,y_pred_NB)

0.7752808988764045

In [44]:
confusion_matrix(y_test,y_pred_NB)

array([[85, 24],
       [16, 53]], dtype=int64)

In [45]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.84      0.78      0.81       109
           1       0.69      0.77      0.73        69

    accuracy                           0.78       178
   macro avg       0.76      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178

# Decision tree

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
model_DT = DecisionTreeClassifier(random_state=42)

In [48]:
model_DT.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [49]:
y_pred_DT = model_DT.predict(X_test_scaled)

In [50]:
y_pred_DT

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1], dtype=int64)

In [51]:
accuracy_score(y_test,y_pred_DT)

0.7584269662921348

In [52]:
confusion_matrix(y_test,y_pred_DT)

array([[88, 21],
       [22, 47]], dtype=int64)

In [53]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.80      0.81      0.80       109
           1       0.69      0.68      0.69        69

    accuracy                           0.76       178
   macro avg       0.75      0.74      0.74       178
weighted avg       0.76      0.76      0.76       178

# Support Vector Machine (SVM)

In [54]:
from sklearn.svm import SVC

In [55]:
model_svm = SVC(kernel = 'rbf')

In [56]:
model_svm.fit(X_train_scaled,y_train)

SVC()

In [57]:
y_pred_svc = model_svm.predict(X_test_scaled)

In [58]:
accuracy_score(y_test,y_pred_svc)

0.8370786516853933

In [59]:
confusion_matrix(y_test,y_pred_svc)

array([[97, 12],
       [17, 52]], dtype=int64)

In [60]:
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87       109
           1       0.81      0.75      0.78        69

    accuracy                           0.84       178
   macro avg       0.83      0.82      0.83       178
weighted avg       0.84      0.84      0.84       178

In [61]:
df

     Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.000000      1      0   7.2500         2
1           1       1    0  38.000000      1      0  71.2833         0
2           1       3    0  26.000000      0      0   7.9250         2
3           1       1    0  35.000000      1      0  53.1000         2
4           0       3    1  35.000000      0      0   8.0500         2
..        ...     ...  ...        ...    ...    ...      ...       ...
886         0       2    1  27.000000      0      0  13.0000         2
887         1       1    0  19.000000      0      0  30.0000         2
888         0       3    0  29.699118      1      2  23.4500         2
889         1       1    1  26.000000      0      0  30.0000         0
890         0       3    1  32.000000      0      0   7.7500         1

[889 rows x 8 columns]

In [63]:
X = df.drop('Survived', axis = 1)
y = df['Survived']

In [64]:
from sklearn.model_selection import cross_val_score

In [66]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [72]:
scores = cross_val_score(knn_model,X_scaled,y,cv = 5,scoring='accuracy')

In [73]:
print(scores)

[0.78089888 0.76966292 0.82022472 0.81460674 0.82485876]

In [74]:
print(scores.mean())

0.8020504030978227